import uuid
import json
from datetime import datetime, timezone
from typing import Dict, Any, List

def _generate_id(type_name: str) -> str:
    return f"{type_name}--{uuid.uuid4()}"

def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")

def generate_stix_bundle(campaign_id: str, incidents: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Generates a STIX 2.1 compliant JSON bundle representing a Threat Campaign
    and all associated Indicators of Compromise (IoCs).
    """
    objects = []
    
    # 1. Create the Campaign Object
    campaign_stix_id = _generate_id("campaign")
    campaign_obj = {
        "type": "campaign",
        "spec_version": "2.1",
        "id": campaign_stix_id,
        "created": _now(),
        "modified": _now(),
        "name": f"Email Threat Campaign: {campaign_id}",
        "description": f"Automated attribution cluster generated by Graph Analytics engine for {len(incidents)} incidents.",
        "objective": "Unknown (Phishing / Fraud)",
    }
    objects.append(campaign_obj)
    
    # 2. Extract unique IoCs across all incidents in the campaign
    ips = set()
    domains = set()
    sender_emails = set()
    
    for inc in incidents:
        if inc.get("origin_ip"): ips.add(inc["origin_ip"])
        if inc.get("sender_domain"): domains.add(inc["sender_domain"])
        if inc.get("from_address"):
            addr = inc["from_address"]
            if "@" in addr:
                clean_addr = addr.split("<")[-1].strip(">").strip()
                sender_emails.add(clean_addr)
                
    # 3. Create Indicator Objects for each IoC and link to Campaign
    def add_indicator(pattern: str, name: str, indicator_type: str):
        ind_id = _generate_id("indicator")
        indicator = {
            "type": "indicator",
            "spec_version": "2.1",
            "id": ind_id,
            "created": _now(),
            "modified": _now(),
            "name": name,
            "pattern": pattern,
            "pattern_type": "stix",
            "valid_from": _now(),
            "indicator_types": [indicator_type]
        }
        objects.append(indicator)
        
        # Link Indicator -> Campaign
        rel = {
            "type": "relationship",
            "spec_version": "2.1",
            "id": _generate_id("relationship"),
            "created": _now(),
            "modified": _now(),
            "relationship_type": "indicates",
            "source_ref": ind_id,
            "target_ref": campaign_stix_id
        }
        objects.append(rel)
        
    for ip in ips:
        add_indicator(f"[ipv4-addr:value = '{ip}']", f"Malicious Origin IP: {ip}", "malicious-activity")
        
    for dom in domains:
        if dom and dom != "unknown":
            add_indicator(f"[domain-name:value = '{dom}']", f"Fraudulent Sender Domain: {dom}", "malicious-activity")
            
    for email in sender_emails:
        add_indicator(f"[email-addr:value = '{email}']", f"Threat Actor Address: {email}", "malicious-activity")
        
    # Return Bundle
    return {
        "type": "bundle",
        "id": _generate_id("bundle"),
        "objects": objects
    }
